<div class="container">
  <div class="row">

    <div class="card-chamado">
      <div class="card">
        <div class="card-header">
          Abertura de chamado
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col">

              <form action="/criar-chamado" method="post">
                <div class="form-group">
                  <label>Título</label>
                  <input required name="title" type="text" class="form-control" placeholder="Título">
                </div>

                <div class="form-group">
                  <label>Categoria</label>
                  <select required name="category" class="form-control">
                    <option>Criação Usuário</option>
                    <option>Impressora</option>
                    <option>Hardware</option>
                    <option>Software</option>
                    <option>Rede</option>
                  </select>
                </div>

                <div class="form-group">
                  <label>Descrição</label>
                  <textarea required name="description" class="form-control" rows="3"></textarea>
                </div>

                <div class="row mt-5">
                  <div class="col-6">
                    <a href="home" class="btn btn-lg btn-warning btn-block">Voltar</a>
                  </div>

                  <div class="col-6">
                    <button class="btn btn-lg btn-info btn-block" type="submit">Abrir</button>
                  </div>
                </div>
              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>