<div class="container">
  <div class="row">

    <div class="card-chamado">
      <div class="card">
        <div class="card-header">
          Consulta de chamado
        </div>

        <div class="card-body">
          <?php
          foreach ($this->view->data as $chamado) {
          ?>
            <div class="card mb-3 bg-light">
              <div class="card-body">
                <h5 class="card-title">
                  <?= $chamado['titulo'];
                  ?>
                </h5>
                <h6 class="card-subtitle mb-2 text-muted">
                  <?= $chamado['categoria'];
                  ?>
                </h6>
                <p class="card-text">
                  <?= $chamado['descricao'];
                  ?>
                </p>
              </div>
            </div>
          <?php
          }
          ?>
          <div class="row mt-5">
            <div class="col-6">
              <a href="/home" class="btn btn-lg btn-warning btn-block">Voltar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>