<div class="container">
  <div class="row">

    <div class="card-consultar-chamado">
      <div class="card">
        <div class="card-header">
          Consulta de chamado
        </div>

        <div class="card-body">
          <?php
          //foreach ($calls as $called) {
          //$text = explode('#', $called);
          ?>

          <!-- <div class="card mb-3 bg-light">
                <div class="card-body">
                  <h5 class="card-title">
                    <?php echo $text[0]; ?>
                  </h5>
                  <h6 class="card-subtitle mb-2 text-muted">
                    <?php echo $text[1]; ?>
                  </h6>
                  <p class="card-text">
                    <?php echo $text[2]; ?>
                  </p>

                </div>
              </div> -->
          <?php
          //}
          ?>
          <div class="row mt-5">
            <div class="col-6">
              <a href="../pages/home.php" class="btn btn-lg btn-warning btn-block">Voltar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>