<div class="container">
  <div class="row">
    <div class="card-login">
      <div class="card">
        <div class="card-header">
          Login
        </div>
        <div class="card-body">
          <?php
          if (isset($_GET['auth'])) {
          ?>
            <div class="text-danger">
              Você precisa fazer login para acessar as páginas.
            </div>
          <?php
          }
          ?>
          <form action="/login" method="post">
            <div class="form-group">
              <input name="email" type="email" class="form-control" placeholder="E-mail">
            </div>
            <div class="form-group">
              <input name="password" type="password" class="form-control" placeholder="Senha">
            </div>
            <?php if (isset($_GET['login'])) { ?>
              <div class="text-danger">
                Email ou senha invalidos
              </div>
            <?php } ?>
            <button class="btn btn-lg btn-info btn-block" type="submit">Entrar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>